apiVersion: batch/v1
kind: CronJob
metadata:
  name: blogposts-generator
  namespace: josh-sizer-dev
spec:
  schedule: "36 20 * * *"
  timeZone: "America/New_York"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: blogposts-generator
            image: joshsizer/blogposts-generator:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: blogposts-generator
            - configMapRef:
                name: blogposts-generator
          restartPolicy: OnFailure
