apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: josh-sizer-dev
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: blogposts-generator
            image: joshsizer/blogposts-generator:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          envFrom:
          - secretRef:
              name: blogposts-generator
          - configMapRef:
              name: blogposts-generator
