---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joshsizer-ghost
  namespace: joshsizer-josh-sizer-dev
spec:
  chart:
    spec:
      chart: ghost
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    existingSecret: "ghost"
    ghostBlogTitle: "An AI Blog"
    ghostHost: &ghostHost "josh.sizer.dev"
    ghostPath: &ghostPath "/"
    service:
      # Default is a LoadBalancer, but I'm deferring to the ingress for that
      type: "ClusterIP"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-staging
      pathType: Prefix
      hostname: *ghostHost
      path: *ghostPath
      tls: true
