---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: josh-sizer-dev
spec:
  chart:
    spec:
      chart: ghost
      version: "21.*.*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    replicaCount: 1
    updateStrategy:
      type: Recreate
    existingSecret: "ghost"
    ghostUsername: "joshsizer"
    ghostEmail: "joshsizer@gmail.com"
    ghostBlogTitle: "a (mostly) ai blog"
    ghostHost: &ghostHost "josh.sizer.dev"
    ghostPath: &ghostPath "/ai-blog"
    ghostEnableHttps: true
    image:
      repository: joshsizer/ghost
      tag: 5.93.0-debian-12-r0
    service:
      # Default is a LoadBalancer, but I'm deferring to the ingress for that
      type: "ClusterIP"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-production
      pathType: Prefix
      hostname: *ghostHost
      path: *ghostPath
      tls: true
    mysql:
      primary:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      auth:
        existingSecret: ghost-mysql
