---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: josh-sizer-dev
spec:
  chart:
    spec:
      chart: ghost
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    existingSecret: "ghost"
    ghostUsername: "joshsizer"
    ghostEmail: "joshsizer@gmail.com"
    ghostBlogTitle: "a (mostly) ai blog"
    ghostHost: &ghostHost "josh.sizer.dev"
    ghostPath: &ghostPath "/"
    ghostEnableHttps: true
    service:
      # Default is a LoadBalancer, but I'm deferring to the ingress for that
      type: "ClusterIP"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-production
      pathType: Prefix
      hostname: *ghostHost
      path: *ghostPath
      tls: true
    mysql:
      primary:
        # configuration: |-
        #   [mysqld]
        #   authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
        #   skip-name-resolve
        #   explicit_defaults_for_timestamp
        #   basedir=/opt/bitnami/mysql
        #   plugin_dir=/opt/bitnami/mysql/lib/plugin
        #   port={{ .Values.primary.containerPorts.mysql }}
        #   mysqlx={{ ternary 1 0 .Values.primary.enableMySQLX }}
        #   mysqlx_port={{ .Values.primary.containerPorts.mysqlx }}
        #   socket=/opt/bitnami/mysql/tmp/mysql.sock
        #   datadir=/bitnami/mysql/data
        #   tmpdir=/opt/bitnami/mysql/tmp
        #   max_allowed_packet=16M
        #   bind-address=*
        #   pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
        #   log-error=/opt/bitnami/mysql/logs/mysqld.log
        #   character-set-server=UTF8
        #   slow_query_log=0
        #   long_query_time=10.0

        #   [client]
        #   port={{ .Values.primary.containerPorts.mysql }}
        #   socket=/opt/bitnami/mysql/tmp/mysql.sock
        #   default-character-set=UTF8
        #   plugin_dir=/opt/bitnami/mysql/lib/plugin

        #   [manager]
        #   port={{ .Values.primary.containerPorts.mysql }}
        #   socket=/opt/bitnami/mysql/tmp/mysql.sock
        #   pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      auth:
        existingSecret: ghost-mysql
        authenticationPolicy: "sha256_password ,,"
