---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: josh-sizer-dev
  namespace: josh-sizer-dev
spec:
  chart:
    spec:
      chart: chart/
      sourceRef:
        kind: GitRepository
        name: josh-sizer-dev
        namespace: joshsizer-flux-root
  interval: 10m0s
