---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joshsizer-josh-sizer-dev
  namespace: joshsizer-josh-sizer-dev
spec:
  chart:
    spec:
      chart: chart/
      sourceRef:
        kind: GitRepository
        name: joshsizer-josh-sizer-dev
        namespace: joshsizer-flux-root
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
