---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: josh-sizer-dev
spec:
  chart:
    spec:
      chart: nginx
      version: "18.*.*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    serverBlock: |
      server {
        listen 0.0.0.0:8080;
        location /obsidian {
          proxy_pass https://publish.obsidian.md/serve?url=josh.sizer.dev/obsidian/;
          proxy_ssl_server_name on;
          proxy_set_header Host publish.obsidian.md;
        }
      }
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-production
      pathType: Prefix
      hostname: josh.sizer.dev
      path: /obsidian
      tls: true
